#!/usr/bin/env bash
# display DNS record information about a domian and its subdomains
# shellcheck disable=SC2086
func () {
    if [ -z "$2" ]; then
        dig www.${1} |
        # awk '$5 ~ /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/{print "The subdomain www is a " $4 " record and points to " $5}'
        # dig lb-01.${1} |
        # awk '$5 ~ /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
        # dig web-01.${1} |
        # awk '$5 ~ /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/{print "The subdomain web-01 is a " $4 " record and points to " $5}'
        # dig web-02.${1} |
        # awk '$5 ~ /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/{print "The subdomain web-02 is a " $4 " record and points to " $5}'
        awk '$5 ~ /([0-9]{1,3}\.?){4}/{print "The subdomain www is a " $4 " record and points to " $5}'
        dig lb-01.${1} |
        awk '$5 ~ /([0-9]{1,3}\.?){4}/{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
        dig web-01.${1} |
        awk '$5 ~ /([0-9]{1,3}\.?){4}/{print "The subdomain web-01 is a " $4 " record and points to " $5}'
        dig web-02.${1} |
        awk '$5 ~ /([0-9]{1,3}\.?){4}/{print "The subdomain web-02 is a " $4 " record and points to " $5}'
    else
        sub_domain=$2
        # dig ${2}.${1} |
        # awk '$5 ~ /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/{print "The subdomain '$sub_domain' is a " $4 " record and points to " $5}'
        dig ${2}.${1} |
        awk '$5 ~ /([0-9]{1,3}\.?){4}/{print "The subdomain '$sub_domain' is a " $4 " record and points to " $5}'
    fi
}

func "$1" "$2"
