#!/usr/bin/env bash
# configures a new Ubuntu machine by installing nginx and
#+ setup nginx to listen on port 80 and return a page that
#+ contains the string 'Hello World!' when querying Nginx at its
#+ root '/' with a GET request (requesting a page) using 'curl'
sudo apt-get update
sudo apt-get install -y nginx
/etc/init.d/nginx start
echo "Hello World!" > /var/www/html/index.html
nginx -s reload
