#!/usr/bin/env bash
# configures a new Ubuntu machine by installing nginx and
#+ setup nginx to listen on port 80 and return a page that
#+ contains the string 'Hello World!' when querying Nginx at its
#+ root '/' with a GET request (requesting a page) using 'curl' and
#+ /redirect_me is redirecting to “301 Moved Permanently”
sudo apt-get update
sudo apt-get install -y nginx
/etc/init.d/nginx start
echo "Hello World!" > /var/www/html/index.html
sed -i "/listen 80 default_server;/a \
\
    location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }" /etc/nginx/sites-available/default
sudo service nginx restart
