#!/usr/bin/env bash
# configures a new Ubuntu machine by installing nginx and
#+ setup nginx to listen on port 80 and return a page that
#+ contains the string 'Hello World!' when querying Nginx at its
#+ root '/' with a GET request (requesting a page) using 'curl', and
#+ /redirect_me is redirecting to “301 Moved Permanently”, and
#+ to have a custom 404 page that contains the string 'Ceci n'est pas une page'
sudo apt-get update
sudo apt-get install -y nginx
/etc/init.d/nginx start
echo "Hello World!" > /var/www/html/index.html
sed -i "/listen 80 default_server;/a \
\
    location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
errreplacement="server_name _;\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$errreplacement/" /etc/nginx/sites-available/default
sudo service nginx restart
