#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo "frontend load_balancer
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web01 18.206.208.78:80 check
    server web02 54.162.233.113:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
