#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo "frontend load_balancer
    bind *:80
    default_backend web_servers
backend web_servers
    balance roundrobin
    server web01 18.206.208.78:80
    server web02 54.162.233.113:80" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy start
