#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
mysqldump -uroot -p"${1}" --all-databases > backup.sql
ARCHIVE_NAME="$(date +%d-%m-%Y)".tar.gz
tar -cvf "$ARCHIVE_NAME" backup.sql
