#!/usr/bin/env bash
# Creates the file `/var/run/myscript.pid` containing this scripts PID
# Displays `To infinity and beyond` indefinitely
# Displays `I hate the kill command` when receiving a SIGTERM signal
# Displays `Y U no love me?!` when receiving a SIGINT signal
# Deletes the file `/var/run/myscript.pid` and terminates itself when receiving
#+ a SIGQUIT or SIGTERM signal
echo $$ | sudo tee "/var/run/myscript.pid" > /dev/null
while true; do

    trap 'echo "I hate the kill command"; sudo rm "/var/run/myscript.pid"; break' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm "/var/run/myscript.pid"; break' SIGQUIT
    echo "To infinity and beyond"
    sleep 2
done
