#!/usr/bin/env bash
# Displays the content of the file /etc/passwd. Displays only the username,
#+ user id, and home directory path for each user.
while [ -e "/etc/passwd" ]; do
    cut -d : -f 1,3,7 < "/etc/passwd"
    break
done
