#!/usr/bin/env bash
# Displays the content of the file /etc/passwd. Displays only the username,
#+ user id, and home directory path for each user.

IFS=":"
exec < /etc/passwd
while read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND; do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. \
$USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done
