#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, and displays this data from the Apache log file,
#+ ordered from the greatest to the lowest number of occurrences in a list format.

awk '{print $1, $9}' "apache-access.log" | sort | uniq -c | sort -nr
