#!/usr/bin/env bash
#  Displays the content of the current directory in a list format,
#+ where only the part of the name after the first dash is displayed 
for file in *; do
    [ -e "$file" ] || continue
    echo "$file" | cut -d - -f 2-
done
