#!/usr/bin/env bash
# a Bash script that resolves localhost to 127.0.0.2 and facebook.com to 8.8.8.8.
cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost//g" ~/hosts.new
sed -i "s/.*facebook.com//g" ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
