#!/usr/bin/env bash
# Configures nginx so that its running as nginx user and listening on all active IPs on port 8080
pkill -f apache
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i '1s/^/user nginx;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx /var/log/nginx /run
# service nginx stop
sudo -u nginx service nginx restart
