#!/usr/bin/env bash
# Configures nginx so that its running as nginx user and listening on all active IPs on port 8080
useradd nginx
sed -i 's/80/8080/' /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx /var/log/nginx /run
service nginx stop
pkill -f nginx
sudo -u nginx nginx -c /etc/nginx/nginx.conf
