#!/usr/bin/env bash
# Configures nginx
pkill -f apache
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i "s/#user www.data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
